# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-22 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('comments', models.TextField(blank=True, default='')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('comments', models.TextField(blank=True, default='')),
                ('level', models.PositiveIntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('parent_theme', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_themes', to='catalogue.Theme')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='person',
            old_name='function',
            new_name='functions',
        ),
        migrations.AddField(
            model_name='ressource',
            name='themes',
            field=models.ManyToManyField(to='catalogue.Theme'),
        ),
        migrations.AddField(
            model_name='person',
            name='themes',
            field=models.ManyToManyField(to='catalogue.Theme'),
        ),
    ]
