# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-22 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20171222_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRessource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('comments', models.TextField(blank=True, default='')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ressource',
            name='type_ressource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogue.TypeRessource'),
            preserve_default=False,
        ),
    ]
