# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-22 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20171222_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='url',
            new_name='link_url',
        ),
    ]
